name: Deploy Docs Website

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
        env:
          GRANAX_TOR_VERSION: 10.0.15

      - name: Generate
        run: npm run nuxt:generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
